### ISSUE TITLE
Adding non-breaking space as a valid character before URL [fix attached]

### ISSUE THREAD

**Issue by Marooned-MB** [iamcal/lib_autolink#11]
I've stumble upon a problem that not every links in the text were highlighted. Insight showed that before those not highlighted there was non-breaking space `&nbsp;`. The solution is quite easy. Change this:
`if (!preg_match('![\s\(\[\{>]$!s', $pre)){`
into this
`if (!preg_match('![\x{00a0}\s\(\[\{>]$!s', $pre)){`

Sorry, I don't know how to suggest a patch here hence the new issue.

**Comment by stof** [comment]
#14 fixed it (in an even more generic way that the suggested patch)
