### ISSUE TITLE
Is there a JS version of this as well?

### ISSUE THREAD

**Issue by seabasss** [iamcal/lib_autolink#16]
Love this little script, but is there a JS version of it as well? Right now I send user data back to the client to apply this script but would be nice to only do it on load.

Awesome work! Thanks!

**Comment by iamcal** [comment]
there isn't currently, although porting it to JS would not be too difficult

**Comment by seabasss** [comment]
> there isn't currently, although porting it to JS would not be too difficult

@iamcal Would you be open to/have time to help me do it? If so, name your price :) Thank you!

**Comment by iamcal** [comment]
I took a stab at starting to port it over. It's not fully working yet, but many of the tests pass: https://github.com/iamcal/autolink-js

**Comment by iamcal** [comment]
All the tests are now passing. It's lacking much documentation and test coverage could be improved, but it has the same functionality as this PHP version

**Comment by seabasss** [comment]
That's awesome! Thank you so much!! :)
